/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testov_JniInterface */

#ifndef _Included_com_example_testov_JniInterface
#define _Included_com_example_testov_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testov_JniInterface
 * Method:    testOV
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testov_JniInterface_testOV
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
